name: C/C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:trusty
    env:
      MATRIX_EVAL: "CC=gcc-7 && CXX=g++-7"
      QT_BASE_DIR: "/opt/qt56"
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:beineri/opt-qt562-trusty
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-7 cmake libbotan1.10-dev libqrencode-dev libzbar-dev
          sudo apt-get install -y qt56base git
          eval ${MATRIX_EVAL}
          # Install a newer version of CMake
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y software-properties-common lsb-release
          sudo apt-get clean all
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://cmake.org/files/v3.22/cmake-3.22.1-Linux-x86_64.sh
          sudo mkdir /opt/cmake
          sudo sh cmake-3.22.1-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
          sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
          cmake --version
      - name: Check out the repository code
        uses: actions/checkout@v2
      - name: Check out libQtShadowsocks code
        run: |
          git clone https://github.com/shadowsocks/libQtShadowsocks.git
          mkdir libQtShadowsocks/build
          cd libQtShadowsocks/build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DQt5Core_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Core" -DQt5Network_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Network" -DQt5Test_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Test"
          make
          sudo make install
      - name: Build project
        run: |
          mkdir build && cd build
          cmake .. -DQt5Core_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Core" -DQt5Network_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Network" -DQt5Gui_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Gui" -DQt5Widgets_DIR="${QT_BASE_DIR}/lib/cmake/Qt5Widgets" -DQt5DBus_DIR="${QT_BASE_DIR}/lib/cmake/Qt5DBus"
          make
